# Generated by Django 2.2.6 on 2019-10-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=1)),
                ('gaji', models.FloatField()),
                ('existing', models.BooleanField()),
                ('occupation', models.CharField(choices=[('N', 'Non-Fix'), ('F', 'Fix')], default='N', max_length=1)),
                ('alamat', models.TextField()),
                ('kendaraan', models.ManyToManyField(to='cust.Vehicle')),
            ],
        ),
    ]
